# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: BuildAndPublish
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/publish'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
        ArtifactName: 'MVCAgileProcess'

- stage: Deploy
  jobs:
  - deployment: DeployToIIS
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'MVCAgileProcess'
              WebsitePhysicalPath: 'C:\inetpub\wwwroot\MVCAgileProcess'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/MVCAgileProcess'
              Contents: '**'
              TargetFolder: 'C:\inetpub\wwwroot\MVCAgileProcess'