# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: BuildAndPublish
    pool:
      vmImage: 'windows-latest'
    steps:
    # Verbose Logging
    - powershell: |
        Write-Host "Pipeline Workspace: $(Pipeline.Workspace)"
        Write-Host "Build ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
        Write-Host "Agent Build Directory: $(Agent.BuildDirectory)"
      displayName: 'Debug Pipeline Paths'

    # Comprehensive Publish
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/publish'
        zipAfterPublish: true
      displayName: 'Publish Project'

    # Artifact Publication with Detailed Logging
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
        ArtifactName: 'MVCAgileProcess'
      displayName: 'Publish Artifacts'

- stage: Deploy
  jobs:
  - deployment: DeployToIIS
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          # Detailed Deployment Logging
          - powershell: |
              Write-Host "Deployment Workspace: $(Pipeline.Workspace)"
              Get-ChildItem "$(Pipeline.Workspace)" -Recurse
            displayName: 'List Deployment Artifacts'

          # Explicit File Copy
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/MVCAgileProcess'
              Contents: '**'
              TargetFolder: 'C:\inetpub\wwwroot\MVCAgileProcess'
            displayName: 'Copy Deployment Files'

          # Extraction Verification
          - powershell: |
              $destination = 'C:\inetpub\wwwroot\MVCAgileProcess'
              Write-Host "Deployment Folder Contents:"
              Get-ChildItem $destination -Recurse | 
                Format-Table FullName, Length, LastWriteTime
            displayName: 'Verify Deployment'